2017-12-03 17:49:22.574 [info] <0.31.0> Application lager started on node nonode@nohost
2017-12-03 17:49:22.757 [error] <0.626.0>@utils_env:default_app:30 CRASH REPORT Process <0.626.0> with 0 neighbours exited with reason: no match of right hand value undefined in utils_env:default_app/0 line 30 in gen_server:init_it/6 line 352
2017-12-03 17:49:22.760 [error] <0.625.0>@utils_env:default_app:30 Supervisor up_config_sup had child up_config_svr started with up_config_svr:start_link() at undefined exit with reason no match of right hand value undefined in utils_env:default_app/0 line 30 in context start_error
2017-12-03 17:49:22.762 [error] <0.623.0> CRASH REPORT Process <0.623.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...} in application_master:init/4 line 134
2017-12-03 17:49:22.765 [info] <0.31.0> Application up_config exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...}
2017-12-03 17:50:41.695 [info] <0.31.0> Application lager started on node nonode@nohost
2017-12-03 17:50:41.888 [error] <0.626.0>@utils_env:default_app:30 CRASH REPORT Process <0.626.0> with 0 neighbours exited with reason: no match of right hand value undefined in utils_env:default_app/0 line 30 in gen_server:init_it/6 line 352
2017-12-03 17:50:41.890 [error] <0.625.0>@utils_env:default_app:30 Supervisor up_config_sup had child up_config_svr started with up_config_svr:start_link() at undefined exit with reason no match of right hand value undefined in utils_env:default_app/0 line 30 in context start_error
2017-12-03 17:50:41.892 [error] <0.623.0> CRASH REPORT Process <0.623.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...} in application_master:init/4 line 134
2017-12-03 17:50:41.893 [info] <0.31.0> Application up_config exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...}
2017-12-03 17:54:34.523 [info] <0.31.0> Application lager started on node nonode@nohost
2017-12-03 17:54:34.696 [error] <0.720.0>@utils_env:default_app:30 CRASH REPORT Process <0.720.0> with 0 neighbours exited with reason: no match of right hand value undefined in utils_env:default_app/0 line 30 in gen_server:init_it/6 line 352
2017-12-03 17:54:34.699 [error] <0.719.0>@utils_env:default_app:30 Supervisor up_config_sup had child up_config_svr started with up_config_svr:start_link() at undefined exit with reason no match of right hand value undefined in utils_env:default_app/0 line 30 in context start_error
2017-12-03 17:54:34.699 [error] <0.717.0> CRASH REPORT Process <0.717.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...} in application_master:init/4 line 134
2017-12-03 17:54:34.700 [info] <0.31.0> Application up_config exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...}
2017-12-03 17:54:35.273 [error] <0.725.0>@xm_up_config:load_public_key:283 load public key from <<"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xm_up_config/priv//keys/B8999001.pub">> failed!set it to <<>>
2017-12-03 17:54:35.331 [info] <0.31.0> Application xm_up_config started on node nonode@nohost
2017-12-03 17:54:37.051 [info] <0.31.0> Application mnesia started on node nonode@nohost
2017-12-03 17:54:37.341 [error] <0.805.0>@pg_convert:do_convert:215 Error =undef,stacktrace=
    lists:foldl/3 line 1263
    pg_convert:'-convert/3-fun-4-'/4 line 102
    lists:foldl/3 line 1263
    pg_convert:'-do_convert/4-fun-4-'/5 line 210
    pg_convert:do_convert_one_op/5 line 335
    pg_xm_up_protocol_req_bankcard:mer_id/1 line 140
    pg_xm_up_protocol_req_bankcard:xm_up_mer_id/1 line 133
    pg_up_protocol:repo_module(mchants)
2017-12-03 17:54:37.341 [error] <0.805.0>@pg_convert:do_convert:216 MFrom = pg_mcht_protocol,MModel = pg_mcht_protocol_req_xm_up_bankcard,Model = {pg_mcht_protocol_req_xm_up_bankcard,<<"000003">>,<<"20171202">>,<<"160309">>,<<"1512201789372">>,<<"oGoeRE/5k+6+UOcw02Th36zmU7yNBhDrpL6hOhbahe7hQVzpnuZW+zSVf1sbQAHCANUL2DfUVsXkSjRKuj7pAkMmuVam/hHlG4MbhmgU5iShLvtQgaMDOetXpbIeJJN4xnXoFjhCmaSG7sM5O+XugCfVGh0SA5uIHjAAs2DS1Eg=">>,<<"6225220113392773">>,<<"01">>,<<"220625198910180328">>,<<232,181,181,233,135,145,231,142,178>>,<<"13721422283">>,xm_up_bankcard,waiting},OpTuple = {customer_code,{#Fun<pg_xm_up_protocol_req_bankcard.22.33981244>,[mcht_id]}},Acc=[]
2017-12-03 17:57:00.189 [info] <0.31.0> Application lager started on node nonode@nohost
2017-12-03 17:57:00.364 [error] <0.750.0>@utils_env:default_app:30 CRASH REPORT Process <0.750.0> with 0 neighbours exited with reason: no match of right hand value undefined in utils_env:default_app/0 line 30 in gen_server:init_it/6 line 352
2017-12-03 17:57:00.364 [error] <0.749.0>@utils_env:default_app:30 Supervisor up_config_sup had child up_config_svr started with up_config_svr:start_link() at undefined exit with reason no match of right hand value undefined in utils_env:default_app/0 line 30 in context start_error
2017-12-03 17:57:00.365 [error] <0.747.0> CRASH REPORT Process <0.747.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...} in application_master:init/4 line 134
2017-12-03 17:57:00.366 [info] <0.31.0> Application up_config exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...}
2017-12-03 17:57:00.956 [error] <0.755.0>@xm_up_config:load_public_key:283 load public key from <<"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xm_up_config/priv//keys/B8999001.pub">> failed!set it to <<>>
2017-12-03 17:57:01.014 [info] <0.31.0> Application xm_up_config started on node nonode@nohost
2017-12-03 17:57:02.802 [info] <0.31.0> Application mnesia started on node nonode@nohost
2017-12-03 18:06:02.293 [info] <0.31.0> Application lager started on node nonode@nohost
2017-12-03 18:06:02.467 [error] <0.720.0>@utils_env:default_app:30 CRASH REPORT Process <0.720.0> with 0 neighbours exited with reason: no match of right hand value undefined in utils_env:default_app/0 line 30 in gen_server:init_it/6 line 352
2017-12-03 18:06:02.478 [error] <0.719.0>@utils_env:default_app:30 Supervisor up_config_sup had child up_config_svr started with up_config_svr:start_link() at undefined exit with reason no match of right hand value undefined in utils_env:default_app/0 line 30 in context start_error
2017-12-03 18:06:02.478 [error] <0.717.0> CRASH REPORT Process <0.717.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...} in application_master:init/4 line 134
2017-12-03 18:06:02.479 [info] <0.31.0> Application up_config exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...}
2017-12-03 18:06:03.055 [error] <0.725.0>@xm_up_config:load_public_key:283 load public key from <<"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xm_up_config/priv//keys/B8999001.pub">> failed!set it to <<>>
2017-12-03 18:06:03.111 [info] <0.31.0> Application xm_up_config started on node nonode@nohost
2017-12-03 18:06:04.835 [info] <0.31.0> Application mnesia started on node nonode@nohost
2017-12-03 18:07:36.740 [info] <0.31.0> Application lager started on node nonode@nohost
2017-12-03 18:07:36.923 [error] <0.720.0>@utils_env:default_app:30 CRASH REPORT Process <0.720.0> with 0 neighbours exited with reason: no match of right hand value undefined in utils_env:default_app/0 line 30 in gen_server:init_it/6 line 352
2017-12-03 18:07:36.925 [error] <0.719.0>@utils_env:default_app:30 Supervisor up_config_sup had child up_config_svr started with up_config_svr:start_link() at undefined exit with reason no match of right hand value undefined in utils_env:default_app/0 line 30 in context start_error
2017-12-03 18:07:36.926 [error] <0.717.0> CRASH REPORT Process <0.717.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...} in application_master:init/4 line 134
2017-12-03 18:07:36.927 [info] <0.31.0> Application up_config exited with reason: {{shutdown,{failed_to_start_child,up_config_svr,{{badmatch,undefined},[{utils_env,default_app,0,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,30}]},{utils_env,get_path,1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,68}]},{utils_env,'-get_path/1-lc$^0/1-0-',1,[{file,"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xfutils/src/utils_env.erl"},{line,77}]},{utils_env,...},...]}}},...}
2017-12-03 18:07:37.501 [error] <0.725.0>@xm_up_config:load_public_key:283 load public key from <<"/mnt/e/pingjianwei/pg-apps/pg_xm_up_protocol/_build/default/lib/xm_up_config/priv//keys/B8999001.pub">> failed!set it to <<>>
2017-12-03 18:07:37.565 [info] <0.31.0> Application xm_up_config started on node nonode@nohost
2017-12-03 18:07:39.286 [info] <0.31.0> Application mnesia started on node nonode@nohost
